[package]
name = "life"
version = "0.1.0"
authors = ["stmtk1 <13043069@gakushuin.ac.jp>"]

[dependencies]
piston_window = "0.85.0"
piston = "0.39.0"
piston2d-graphics = "0.28.0"
pistoncore-glutin_window = "0.51.1"
piston2d-opengl_graphics = "0.57.0"
rand="0.6.4"
